### ISSUE TITLE
Add quickstart module

### ISSUE THREAD

**Issue by martin-g** [ageery/kwicket#1]
Awesome work!

You might want to add a quickstart module to make it easier to start a new project.
I have one at https://github.com/martin-g/wicket-kotlin-quickstart but it uses Maven.

**Comment by ageery** [comment]
Thanks for the kind words, Martin!

I created a kwicket-starter project (
https://github.com/ageery/kwicket-starter) that has both Maven and Gradle
build examples.

**Comment by martin-g** [comment]
Nice!
I didn't check for other projects, but just the sub-modules.

Closing this issue!
